### ISSUE TITLE
PHP Runtime Deprecation Notice

### ISSUE THREAD

**Issue by MarkusBausK** [nitsan-technologies/ns_license#10]
PHP Runtime Deprecation Notice: Creation of dynamic property NITSAN\NsLicense\Service\LicenseService::$packageManager is deprecated in /var/www/html/vendor/nitsan/ns-license/Classes/Service/LicenseService.php line 27

TYPO3 13.4.0-dev (Running locally on DDEV)
PHP 8.3

**Comment by nitsan-technologies** [comment]
Hello @MarkusBausK 

Thank you for bringing this to our attention! The deprecation notice occurred because we were actively working on that branch at the time. However, we have since resolved this issue, and a new release tag has been published, which works well with PHP 8.3. Please update to the latest version, and you should no longer encounter this issue.

Best Regards,
Team NITSAN
